
"""initial schema

迁移编号：7d4fbd959d06
修订内容：initial schema
生成时间：2026-09-20 00:16:43.957809
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# 迁移标识
revision: str = '7d4fbd959d06'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级到本版本结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('medical_record_no', sa.String(length=64), nullable=False),
    sa.Column('current_state', sa.String(length=8), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('stage_goal', sa.String(length=255), nullable=True),
    sa.Column('interventions', sa.String(length=255), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('last_med_stop_date', sa.Date(), nullable=True),
    sa.Column('lifestyle_start_date', sa.Date(), nullable=True),
    sa.Column('surgery_date', sa.Date(), nullable=True),
    sa.Column('earliest_judge_date', sa.Date(), nullable=True),
    sa.Column('remission_confirmed_date', sa.Date(), nullable=True),
    sa.Column('has_glucose_lowering_drug', sa.Boolean(), nullable=True),
    sa.Column('drug_purpose', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_current_state'), 'patients', ['current_state'], unique=False)
    op.create_index(op.f('ix_patients_medical_record_no'), 'patients', ['medical_record_no'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_operator_id'), 'audit_log', ['operator_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('source_state', sa.String(length=8), nullable=False),
    sa.Column('target_state', sa.String(length=8), nullable=False),
    sa.Column('template_id', sa.String(length=32), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_operator_id'), 'events', ['operator_id'], unique=False)
    op.create_index(op.f('ix_events_patient_id'), 'events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_events_request_id'), 'events', ['request_id'], unique=False)
    op.create_index(op.f('ix_events_rule_id'), 'events', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退到上一版本结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_rule_id'), table_name='events')
    op.drop_index(op.f('ix_events_request_id'), table_name='events')
    op.drop_index(op.f('ix_events_patient_id'), table_name='events')
    op.drop_index(op.f('ix_events_operator_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_audit_log_operator_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_medical_record_no'), table_name='patients')
    op.drop_index(op.f('ix_patients_current_state'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('app_meta')
    # ### end Alembic commands ###
